name: 'rust-toolchain-reborn'
description: 'Install the Rust toolchain'
author: 'placintaalexandru team'
branding:
  icon: activity
  color: orange
inputs:
  toolchain:
    description: Rust toolchain name.
    required: false
  profile:
    description: Name of the group of components to be installed for a new toolchain
    required: false
  components:
    description: Comma-separated list of components to be additionally installed for a new toolchain
    required: false
  targets:
    description: Target triple to install for this toolchain
    required: false
  default:
    description: Set installed toolchain as default
    required: false
    default: "false"
  override:
    description: Set installed toolchain as an override for a directory
    required: false
    default: "false"
  force:
    description: Force an update, even if some components are missing
    required: false
    default: "false"
outputs:
  rustc:
    description: Installed Rustc version
  rustc_hash:
    description: Installed Rustc version hash, can be used for caching purposes
  cargo:
    description: Installed Cargo version
  rustup:
    description: Installed rustup version
runs:
  using: node20
  main: dist/index.js
